server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /message-service/api


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/message_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect # we are adding this to tell other platforms to use postgre

#  security:
#    user:
#      name: postgres
#      password: postgres
logging:
  file:
    name: logs/message.log # We are gonna log everything
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
    level:
      org.springframework.web: DEBUG # We will log if we run in the debug mode.
      com.messageservice.message: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
